In [2]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook; ', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook;  3.7.6


# Exercícios

In [10]:
# Exercício 1 - Crie uma lista de 3 elementos e calcule a terceira potência de cada elemento
a = [2, 4, 8]
list(map(lambda x:x**3, a))

[8, 64, 512]

In [12]:
# Exercício 2 - Reescreva o código abaixo, usando a função map(). O resultado final deve ser o mesmo
palavras = 'A Data Science Academy oferece os melhores curso de análise de dados do Brasi'.split()
resultado = [[w.upper(), w.lower(), len(w)] for w in palavras]
for i in resultado:
    print(i)

['A', 'a', 1]
['DATA', 'data', 4]
['SCIENCE', 'science', 7]
['ACADEMY', 'academy', 7]
['OFERECE', 'oferece', 7]
['OS', 'os', 2]
['MELHORES', 'melhores', 8]
['CURSO', 'curso', 5]
['DE', 'de', 2]
['ANÁLISE', 'análise', 7]
['DE', 'de', 2]
['DADOS', 'dados', 5]
['DO', 'do', 2]
['BRASI', 'brasi', 5]


In [13]:
resultado = map(lambda w: [w.upper(), w.lower(), len(w)], palavras)
for i in resultado:
    print(i)

['A', 'a', 1]
['DATA', 'data', 4]
['SCIENCE', 'science', 7]
['ACADEMY', 'academy', 7]
['OFERECE', 'oferece', 7]
['OS', 'os', 2]
['MELHORES', 'melhores', 8]
['CURSO', 'curso', 5]
['DE', 'de', 2]
['ANÁLISE', 'análise', 7]
['DE', 'de', 2]
['DADOS', 'dados', 5]
['DO', 'do', 2]
['BRASI', 'brasi', 5]


In [19]:
# Exercício 3 - Calcule a matriz transposta da matriz abaixo:
# Caso não saiba o que é matriz transposta, visite este link: https://pt.wikipedia.org/wiki/Matriz_transposta
# Matriz transposta é um conceito fundamental na construção de redes neurais artifíciais, base de sistemas de IA.
matrix = [[1,2], [3,4], [5,6], [7,8]]
print(matrix)

[[1, 2], [3, 4], [5, 6], [7, 8]]


In [18]:
import numpy as np


In [27]:
x = np.array(matrix)
print(x)


print(x.reshape(8,1))


print('A matriz transposta é', x.T)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
A matriz transposta é [[1 3 5 7]
 [2 4 6 8]]


In [28]:
transpose = [[row[i] for row in matrix] for i in range(2)]
print(transpose)

[[1, 3, 5, 7], [2, 4, 6, 8]]
